authors:
  gabrielbdornas:
    name: Gabriel Braico Dornas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/49699290
  labanca:
    name: Andrei Morais Labanca
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/7211451
  carloshob:
    name: Carlos Henrique de Oliveira Brochado
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/19910140
  hslinhares:
    name: Henrique de Souza Linhares
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/43452663
  raianecardoso:
    name: Raiane Cardoso de Souza
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/166438302?v=4
  danielmelo55:
    name: Daniel Melo
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/157495571?v=4